package com.crestech.opkey.plugin;

public enum ResultCodes {

	SUCCESS								(0),
	
	ERROR_OBJECT_NOT_FOUND				(-11100),
	ERROR_OBJECT_NOT_OPERATABLE			(-11200),
	ERROR_TEXT_NOT_FOUND				(-11300),
	ERROR_UNSUPPORTED_OPERATION			(-11400),
		
	ERROR_METHOD_NOT_FOUND				(-12100),
	ERROR_TIMEOUT						(-12200),
		
	ERROR_METHOD_SIGNATURE_MISMATCH		(-13100),
	ERROR_ARGUMENT_DATA_MISSING			(-13200),
	ERROR_ARGUMENT_DATA_INVALID			(-13300),
	ERROR_DATA_TOO_LONG					(-13400),
		
	ERROR_INSUFFICIENT_PRIVILEGES 		(-14100),
	ERROR_UNSATISFIED_DEPENDENCIES		(-14200),
	ERROR_UNEXPECTED_POPUP_DETECTED		(-14300),
	ERROR_CONFLICTING_CONFIGURATION  	(-14400),
	ERROR_CONNECTION_FAILURE  			(-14500),
		
	ERROR_UNHANDLED_EXCEPTION			(-15200),
	
	ERROR_VERIFICATION_FAILLED 			(-16100),
	
	ERROR_USER_ASSERTED_FAILURE 		(-17100),
	
	;

	private final int errorCode;   

	ResultCodes(int index) {
		this.errorCode = index;
	}

	public int Code() { 
		return errorCode; 
	}
}
