//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.11 at 03:47:06 PM IST 
//


package com.crestech.opkey.plugin.communication.contracts.functioncall;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsHybrid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MainActivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WaitForActivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OperatingSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApplicationPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstrumentedAppPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListenerPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayName",
    "isHybrid",
    "_package",
    "mainActivity",
    "waitForActivity",
    "operatingSystem",
    "applicationPath",
    "instrumentedAppPath",
    "listenerPort"
})
@XmlRootElement(name = "MobileApplication")
public class MobileApplication {

    @XmlElement(name = "DisplayName", required = true)
    protected String displayName;
    @XmlElement(name = "IsHybrid")
    protected boolean isHybrid;
    @XmlElement(name = "Package", required = true)
    protected String _package;
    @XmlElement(name = "MainActivity", required = true)
    protected String mainActivity;
    @XmlElement(name = "WaitForActivity", required = true)
    protected String waitForActivity;
    @XmlElement(name = "OperatingSystem", required = true)
    protected String operatingSystem;
    @XmlElement(name = "ApplicationPath", required = true)
    protected String applicationPath;
    @XmlElement(name = "InstrumentedAppPath", required = true)
    protected String instrumentedAppPath;
    @XmlElement(name = "ListenerPort")
    protected int listenerPort;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the isHybrid property.
     * 
     */
    public boolean isIsHybrid() {
        return isHybrid;
    }

    /**
     * Sets the value of the isHybrid property.
     * 
     */
    public void setIsHybrid(boolean value) {
        this.isHybrid = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the mainActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainActivity() {
        return mainActivity;
    }

    /**
     * Sets the value of the mainActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainActivity(String value) {
        this.mainActivity = value;
    }

    /**
     * Gets the value of the waitForActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitForActivity() {
        return waitForActivity;
    }

    /**
     * Sets the value of the waitForActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitForActivity(String value) {
        this.waitForActivity = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingSystem(String value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the applicationPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationPath() {
        return applicationPath;
    }

    /**
     * Sets the value of the applicationPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationPath(String value) {
        this.applicationPath = value;
    }

    /**
     * Gets the value of the instrumentedAppPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentedAppPath() {
        return instrumentedAppPath;
    }

    /**
     * Sets the value of the instrumentedAppPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentedAppPath(String value) {
        this.instrumentedAppPath = value;
    }

    /**
     * Gets the value of the listenerPort property.
     * 
     */
    public int getListenerPort() {
        return listenerPort;
    }

    /**
     * Sets the value of the listenerPort property.
     * 
     */
    public void setListenerPort(int value) {
        this.listenerPort = value;
    }

}
