//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.11 at 03:47:06 PM IST 
//


package com.crestech.opkey.plugin.communication.contracts.functioncall;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UseSmartIdentification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Properties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="RegularExpression" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="IsUsed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="PluginSpecification" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ChildObject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}Object" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="OpKeyType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LogicalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "useSmartIdentification",
    "properties",
    "childObject"
})
@XmlRootElement(name = "Object")
public class Object {

    @XmlElement(name = "UseSmartIdentification")
    protected boolean useSmartIdentification;
    @XmlElement(name = "Properties", required = true)
    protected Object.Properties properties;
    @XmlElement(name = "ChildObject", required = true)
    protected Object.ChildObject childObject;
    @XmlAttribute(name = "OpKeyType", required = true)
    protected String opKeyType;
    @XmlAttribute(name = "LogicalName", required = true)
    protected String logicalName;

    /**
     * Gets the value of the useSmartIdentification property.
     * 
     */
    public boolean isUseSmartIdentification() {
        return useSmartIdentification;
    }

    /**
     * Sets the value of the useSmartIdentification property.
     * 
     */
    public void setUseSmartIdentification(boolean value) {
        this.useSmartIdentification = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Object.Properties }
     *     
     */
    public Object.Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object.Properties }
     *     
     */
    public void setProperties(Object.Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the childObject property.
     * 
     * @return
     *     possible object is
     *     {@link Object.ChildObject }
     *     
     */
    public Object.ChildObject getChildObject() {
        return childObject;
    }

    /**
     * Sets the value of the childObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object.ChildObject }
     *     
     */
    public void setChildObject(Object.ChildObject value) {
        this.childObject = value;
    }

    /**
     * Gets the value of the opKeyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpKeyType() {
        return opKeyType;
    }

    /**
     * Sets the value of the opKeyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpKeyType(String value) {
        this.opKeyType = value;
    }

    /**
     * Gets the value of the logicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalName() {
        return logicalName;
    }

    /**
     * Sets the value of the logicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalName(String value) {
        this.logicalName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}Object" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "object"
    })
    public static class ChildObject {

        @XmlElement(name = "Object")
        protected Object object;

        /**
         * Gets the value of the object property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getObject() {
            return object;
        }

        /**
         * Sets the value of the object property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setObject(Object value) {
            this.object = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="RegularExpression" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="IsUsed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="PluginSpecification" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class Properties {

        @XmlElement(name = "Property")
        protected List<Object.Properties.Property> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object.Properties.Property }
         * 
         * 
         */
        public List<Object.Properties.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<Object.Properties.Property>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="RegularExpression" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="IsUsed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="PluginSpecification" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Property {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "DataType", required = true)
            protected String dataType;
            @XmlAttribute(name = "RegularExpression", required = true)
            protected boolean regularExpression;
            @XmlAttribute(name = "IsUsed", required = true)
            protected boolean isUsed;
            @XmlAttribute(name = "PluginSpecification", required = true)
            protected String pluginSpecification;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataType(String value) {
                this.dataType = value;
            }

            /**
             * Gets the value of the regularExpression property.
             * 
             */
            public boolean isRegularExpression() {
                return regularExpression;
            }

            /**
             * Sets the value of the regularExpression property.
             * 
             */
            public void setRegularExpression(boolean value) {
                this.regularExpression = value;
            }

            /**
             * Gets the value of the isUsed property.
             * 
             */
            public boolean isIsUsed() {
                return isUsed;
            }

            /**
             * Sets the value of the isUsed property.
             * 
             */
            public void setIsUsed(boolean value) {
                this.isUsed = value;
            }

            /**
             * Gets the value of the pluginSpecification property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPluginSpecification() {
                return pluginSpecification;
            }

            /**
             * Sets the value of the pluginSpecification property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPluginSpecification(String value) {
                this.pluginSpecification = value;
            }

        }

    }

}
