//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.11 at 03:47:06 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opkey.crestechglobal.com/xml/functioncall", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.crestech.opkey.plugin.communication.contracts.functioncall;
