//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.09 at 07:32:52 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opkey.crestechglobal.com/xml/EventSubscriptionRequest")
package com.crestech.opkey.plugin.communication.contracts.eventsubscription;
