//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.09 at 07:32:52 PM IST 
//


package com.crestech.opkey.plugin.communication.contracts.eventsubscription;

import javax.xml.bind.annotation.XmlRegistry;
import com.crestech.opkey.plugin.communication.contracts.eventsubscription.EventSubscriptionRequest.Event;
import com.crestech.opkey.plugin.communication.contracts.eventsubscription.EventSubscriptionRequest.Parameters;
import com.crestech.opkey.plugin.communication.contracts.eventsubscription.EventSubscriptionRequest.Parameters.Parameter;
import com.crestech.opkey.plugin.communication.contracts.eventsubscription.EventSubscriptionRequest.Publisher;
import com.crestech.opkey.plugin.communication.contracts.eventsubscription.EventSubscriptionRequest.Subscriber;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.crestech.opkey.plugin.communication.contracts.eventsubscription package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.crestech.opkey.plugin.communication.contracts.eventsubscription
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEventSubscriptionRequestEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createEventSubscriptionRequestParametersParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createEventSubscriptionRequestPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Subscriber }
     * 
     */
    public Subscriber createEventSubscriptionRequestSubscriber() {
        return new Subscriber();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createEventSubscriptionRequestParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link EventSubscriptionRequest }
     * 
     */
    public EventSubscriptionRequest createEventSubscriptionRequest() {
        return new EventSubscriptionRequest();
    }

}
