//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.11 at 03:47:06 PM IST 
//


package com.crestech.opkey.plugin.communication.contracts.functioncall;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StepNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SnapshotRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Function">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="methodName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="callTimeoutInMillis" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ObjectArguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ObjectArgument" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}Object"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataArguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataArgument" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MobilityArguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MobileDeviceArguments">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Device" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileDevice"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MobileApplicationArguments">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Application" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileApplication"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stepNumber",
    "snapshotRequired",
    "function",
    "objectArguments",
    "dataArguments",
    "mobilityArguments"
})
@XmlRootElement(name = "FunctionCall")
public class FunctionCall {

    @XmlElement(name = "StepNumber")
    protected long stepNumber;
    @XmlElement(name = "SnapshotRequired")
    protected boolean snapshotRequired;
    @XmlElement(name = "Function", required = true)
    protected FunctionCall.Function function;
    @XmlElement(name = "ObjectArguments", required = true)
    protected FunctionCall.ObjectArguments objectArguments;
    @XmlElement(name = "DataArguments", required = true)
    protected FunctionCall.DataArguments dataArguments;
    @XmlElement(name = "MobilityArguments", required = true)
    protected FunctionCall.MobilityArguments mobilityArguments;

    /**
     * Gets the value of the stepNumber property.
     * 
     */
    public long getStepNumber() {
        return stepNumber;
    }

    /**
     * Sets the value of the stepNumber property.
     * 
     */
    public void setStepNumber(long value) {
        this.stepNumber = value;
    }

    /**
     * Gets the value of the snapshotRequired property.
     * 
     */
    public boolean isSnapshotRequired() {
        return snapshotRequired;
    }

    /**
     * Sets the value of the snapshotRequired property.
     * 
     */
    public void setSnapshotRequired(boolean value) {
        this.snapshotRequired = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionCall.Function }
     *     
     */
    public FunctionCall.Function getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionCall.Function }
     *     
     */
    public void setFunction(FunctionCall.Function value) {
        this.function = value;
    }

    /**
     * Gets the value of the objectArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionCall.ObjectArguments }
     *     
     */
    public FunctionCall.ObjectArguments getObjectArguments() {
        return objectArguments;
    }

    /**
     * Sets the value of the objectArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionCall.ObjectArguments }
     *     
     */
    public void setObjectArguments(FunctionCall.ObjectArguments value) {
        this.objectArguments = value;
    }

    /**
     * Gets the value of the dataArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionCall.DataArguments }
     *     
     */
    public FunctionCall.DataArguments getDataArguments() {
        return dataArguments;
    }

    /**
     * Sets the value of the dataArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionCall.DataArguments }
     *     
     */
    public void setDataArguments(FunctionCall.DataArguments value) {
        this.dataArguments = value;
    }

    /**
     * Gets the value of the mobilityArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionCall.MobilityArguments }
     *     
     */
    public FunctionCall.MobilityArguments getMobilityArguments() {
        return mobilityArguments;
    }

    /**
     * Sets the value of the mobilityArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionCall.MobilityArguments }
     *     
     */
    public void setMobilityArguments(FunctionCall.MobilityArguments value) {
        this.mobilityArguments = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataArgument" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataArgument"
    })
    public static class DataArguments {

        @XmlElement(name = "DataArgument")
        protected List<FunctionCall.DataArguments.DataArgument> dataArgument;

        /**
         * Gets the value of the dataArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FunctionCall.DataArguments.DataArgument }
         * 
         * 
         */
        public List<FunctionCall.DataArguments.DataArgument> getDataArgument() {
            if (dataArgument == null) {
                dataArgument = new ArrayList<FunctionCall.DataArguments.DataArgument>();
            }
            return this.dataArgument;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DataArgument {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "argumentName", required = true)
            protected String argumentName;
            @XmlAttribute(name = "dataType", required = true)
            protected String dataType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the argumentName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArgumentName() {
                return argumentName;
            }

            /**
             * Sets the value of the argumentName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArgumentName(String value) {
                this.argumentName = value;
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataType(String value) {
                this.dataType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="methodName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="callTimeoutInMillis" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Function {

        @XmlAttribute(name = "methodName", required = true)
        protected String methodName;
        @XmlAttribute(name = "callTimeoutInMillis", required = true)
        protected int callTimeoutInMillis;

        /**
         * Gets the value of the methodName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMethodName() {
            return methodName;
        }

        /**
         * Sets the value of the methodName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMethodName(String value) {
            this.methodName = value;
        }

        /**
         * Gets the value of the callTimeoutInMillis property.
         * 
         */
        public int getCallTimeoutInMillis() {
            return callTimeoutInMillis;
        }

        /**
         * Sets the value of the callTimeoutInMillis property.
         * 
         */
        public void setCallTimeoutInMillis(int value) {
            this.callTimeoutInMillis = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MobileDeviceArguments">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Device" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileDevice"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MobileApplicationArguments">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Application" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileApplication"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mobileDeviceArguments",
        "mobileApplicationArguments"
    })
    public static class MobilityArguments {

        @XmlElement(name = "MobileDeviceArguments", required = true)
        protected FunctionCall.MobilityArguments.MobileDeviceArguments mobileDeviceArguments;
        @XmlElement(name = "MobileApplicationArguments", required = true)
        protected FunctionCall.MobilityArguments.MobileApplicationArguments mobileApplicationArguments;

        /**
         * Gets the value of the mobileDeviceArguments property.
         * 
         * @return
         *     possible object is
         *     {@link FunctionCall.MobilityArguments.MobileDeviceArguments }
         *     
         */
        public FunctionCall.MobilityArguments.MobileDeviceArguments getMobileDeviceArguments() {
            return mobileDeviceArguments;
        }

        /**
         * Sets the value of the mobileDeviceArguments property.
         * 
         * @param value
         *     allowed object is
         *     {@link FunctionCall.MobilityArguments.MobileDeviceArguments }
         *     
         */
        public void setMobileDeviceArguments(FunctionCall.MobilityArguments.MobileDeviceArguments value) {
            this.mobileDeviceArguments = value;
        }

        /**
         * Gets the value of the mobileApplicationArguments property.
         * 
         * @return
         *     possible object is
         *     {@link FunctionCall.MobilityArguments.MobileApplicationArguments }
         *     
         */
        public FunctionCall.MobilityArguments.MobileApplicationArguments getMobileApplicationArguments() {
            return mobileApplicationArguments;
        }

        /**
         * Sets the value of the mobileApplicationArguments property.
         * 
         * @param value
         *     allowed object is
         *     {@link FunctionCall.MobilityArguments.MobileApplicationArguments }
         *     
         */
        public void setMobileApplicationArguments(FunctionCall.MobilityArguments.MobileApplicationArguments value) {
            this.mobileApplicationArguments = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Application" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileApplication"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "application"
        })
        public static class MobileApplicationArguments {

            @XmlElement(name = "Application")
            protected List<FunctionCall.MobilityArguments.MobileApplicationArguments.Application> application;

            /**
             * Gets the value of the application property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the application property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getApplication().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FunctionCall.MobilityArguments.MobileApplicationArguments.Application }
             * 
             * 
             */
            public List<FunctionCall.MobilityArguments.MobileApplicationArguments.Application> getApplication() {
                if (application == null) {
                    application = new ArrayList<FunctionCall.MobilityArguments.MobileApplicationArguments.Application>();
                }
                return this.application;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileApplication"/>
             *       &lt;/sequence>
             *       &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mobileApplication"
            })
            public static class Application {

                @XmlElement(name = "MobileApplication", required = true)
                protected MobileApplication mobileApplication;
                @XmlAttribute(name = "argumentName", required = true)
                protected String argumentName;

                /**
                 * Gets the value of the mobileApplication property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MobileApplication }
                 *     
                 */
                public MobileApplication getMobileApplication() {
                    return mobileApplication;
                }

                /**
                 * Sets the value of the mobileApplication property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MobileApplication }
                 *     
                 */
                public void setMobileApplication(MobileApplication value) {
                    this.mobileApplication = value;
                }

                /**
                 * Gets the value of the argumentName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArgumentName() {
                    return argumentName;
                }

                /**
                 * Sets the value of the argumentName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArgumentName(String value) {
                    this.argumentName = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Device" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileDevice"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "device"
        })
        public static class MobileDeviceArguments {

            @XmlElement(name = "Device")
            protected List<FunctionCall.MobilityArguments.MobileDeviceArguments.Device> device;

            /**
             * Gets the value of the device property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the device property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDevice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FunctionCall.MobilityArguments.MobileDeviceArguments.Device }
             * 
             * 
             */
            public List<FunctionCall.MobilityArguments.MobileDeviceArguments.Device> getDevice() {
                if (device == null) {
                    device = new ArrayList<FunctionCall.MobilityArguments.MobileDeviceArguments.Device>();
                }
                return this.device;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}MobileDevice"/>
             *       &lt;/sequence>
             *       &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mobileDevice"
            })
            public static class Device {

                @XmlElement(name = "MobileDevice", required = true)
                protected MobileDevice mobileDevice;
                @XmlAttribute(name = "argumentName", required = true)
                protected String argumentName;

                /**
                 * Gets the value of the mobileDevice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MobileDevice }
                 *     
                 */
                public MobileDevice getMobileDevice() {
                    return mobileDevice;
                }

                /**
                 * Sets the value of the mobileDevice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MobileDevice }
                 *     
                 */
                public void setMobileDevice(MobileDevice value) {
                    this.mobileDevice = value;
                }

                /**
                 * Gets the value of the argumentName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArgumentName() {
                    return argumentName;
                }

                /**
                 * Sets the value of the argumentName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArgumentName(String value) {
                    this.argumentName = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ObjectArgument" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}Object"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectArgument"
    })
    public static class ObjectArguments {

        @XmlElement(name = "ObjectArgument")
        protected List<FunctionCall.ObjectArguments.ObjectArgument> objectArgument;

        /**
         * Gets the value of the objectArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FunctionCall.ObjectArguments.ObjectArgument }
         * 
         * 
         */
        public List<FunctionCall.ObjectArguments.ObjectArgument> getObjectArgument() {
            if (objectArgument == null) {
                objectArgument = new ArrayList<FunctionCall.ObjectArguments.ObjectArgument>();
            }
            return this.objectArgument;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://opkey.crestechglobal.com/xml/functioncall}Object"/>
         *       &lt;/sequence>
         *       &lt;attribute name="argumentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "object"
        })
        public static class ObjectArgument {

            @XmlElement(name = "Object", required = true)
            protected Object object;
            @XmlAttribute(name = "argumentName", required = true)
            protected String argumentName;

            /**
             * Gets the value of the object property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getObject() {
                return object;
            }

            /**
             * Sets the value of the object property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setObject(Object value) {
                this.object = value;
            }

            /**
             * Gets the value of the argumentName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArgumentName() {
                return argumentName;
            }

            /**
             * Sets the value of the argumentName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArgumentName(String value) {
                this.argumentName = value;
            }

        }

    }

}
