//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.11 at 03:47:06 PM IST 
//


package com.crestech.opkey.plugin.communication.contracts.functioncall;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.crestech.opkey.plugin.communication.contracts.functioncall package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.crestech.opkey.plugin.communication.contracts.functioncall
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FunctionCall }
     * 
     */
    public FunctionCall createFunctionCall() {
        return new FunctionCall();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Object.Properties }
     * 
     */
    public Object.Properties createObjectProperties() {
        return new Object.Properties();
    }

    /**
     * Create an instance of {@link FunctionCall.MobilityArguments }
     * 
     */
    public FunctionCall.MobilityArguments createFunctionCallMobilityArguments() {
        return new FunctionCall.MobilityArguments();
    }

    /**
     * Create an instance of {@link FunctionCall.MobilityArguments.MobileApplicationArguments }
     * 
     */
    public FunctionCall.MobilityArguments.MobileApplicationArguments createFunctionCallMobilityArgumentsMobileApplicationArguments() {
        return new FunctionCall.MobilityArguments.MobileApplicationArguments();
    }

    /**
     * Create an instance of {@link FunctionCall.MobilityArguments.MobileDeviceArguments }
     * 
     */
    public FunctionCall.MobilityArguments.MobileDeviceArguments createFunctionCallMobilityArgumentsMobileDeviceArguments() {
        return new FunctionCall.MobilityArguments.MobileDeviceArguments();
    }

    /**
     * Create an instance of {@link FunctionCall.DataArguments }
     * 
     */
    public FunctionCall.DataArguments createFunctionCallDataArguments() {
        return new FunctionCall.DataArguments();
    }

    /**
     * Create an instance of {@link FunctionCall.ObjectArguments }
     * 
     */
    public FunctionCall.ObjectArguments createFunctionCallObjectArguments() {
        return new FunctionCall.ObjectArguments();
    }

    /**
     * Create an instance of {@link MobileDevice }
     * 
     */
    public MobileDevice createMobileDevice() {
        return new MobileDevice();
    }

    /**
     * Create an instance of {@link MobileApplication }
     * 
     */
    public MobileApplication createMobileApplication() {
        return new MobileApplication();
    }

    /**
     * Create an instance of {@link FunctionCall.Function }
     * 
     */
    public FunctionCall.Function createFunctionCallFunction() {
        return new FunctionCall.Function();
    }

    /**
     * Create an instance of {@link Object.ChildObject }
     * 
     */
    public Object.ChildObject createObjectChildObject() {
        return new Object.ChildObject();
    }

    /**
     * Create an instance of {@link Object.Properties.Property }
     * 
     */
    public Object.Properties.Property createObjectPropertiesProperty() {
        return new Object.Properties.Property();
    }

    /**
     * Create an instance of {@link FunctionCall.MobilityArguments.MobileApplicationArguments.Application }
     * 
     */
    public FunctionCall.MobilityArguments.MobileApplicationArguments.Application createFunctionCallMobilityArgumentsMobileApplicationArgumentsApplication() {
        return new FunctionCall.MobilityArguments.MobileApplicationArguments.Application();
    }

    /**
     * Create an instance of {@link FunctionCall.MobilityArguments.MobileDeviceArguments.Device }
     * 
     */
    public FunctionCall.MobilityArguments.MobileDeviceArguments.Device createFunctionCallMobilityArgumentsMobileDeviceArgumentsDevice() {
        return new FunctionCall.MobilityArguments.MobileDeviceArguments.Device();
    }

    /**
     * Create an instance of {@link FunctionCall.DataArguments.DataArgument }
     * 
     */
    public FunctionCall.DataArguments.DataArgument createFunctionCallDataArgumentsDataArgument() {
        return new FunctionCall.DataArguments.DataArgument();
    }

    /**
     * Create an instance of {@link FunctionCall.ObjectArguments.ObjectArgument }
     * 
     */
    public FunctionCall.ObjectArguments.ObjectArgument createFunctionCallObjectArgumentsObjectArgument() {
        return new FunctionCall.ObjectArguments.ObjectArgument();
    }

}
